# 使用するGolangのイメージを指定する
FROM golang:1.8

# 必要なパッケージなどなどをインストールする
#RUN apt-get update -qq && \
#    apt-get install -y mysql-client vim

# ワーキングディレクトリを指定する
WORKDIR /go/src/api

#docker-compose.ymlの設定につながる
EXPOSE 8080
