# 使用するGolangのイメージを指定する
FROM golang:1.14-alpine

# 必要なパッケージなどなどをインストールする
#RUN apt -y update && apt -y install git
#RUN go get github.com/go-sql-driver/mysql

# ワーキングディレクトリを指定する
WORKDIR /go/src/api

#docker-compose.ymlの設定につながる
EXPOSE 8080
